# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-10-01 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211001_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.CharField(max_length=512, verbose_name='内容')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '已结束')], default=1, verbose_name='状态')),
                ('cover', models.FileField(max_length=128, upload_to='', verbose_name='封面')),
                ('video', models.CharField(blank=True, max_length=128, null=True, verbose_name='预览视频')),
                ('start_time', models.DateTimeField(verbose_name='通知开始时间')),
                ('end_time', models.DateTimeField(verbose_name='通知结束时间')),
                ('look_count', models.PositiveIntegerField(default=0, verbose_name='围观次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '活动系列',
            },
        ),
        migrations.CreateModel(
            name='AgreeMessageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=64, verbose_name='Celery通知任务ID')),
                ('end_task', models.CharField(max_length=64, verbose_name='Celery通知结束任务ID')),
                ('agreeMessage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.AgreeMessage', verbose_name='通知')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='auctionitemdetail',
            name='item',
        ),
        migrations.RemoveField(
            model_name='auctionitemimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='auctiontask',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bidrecord',
            name='item',
        ),
        migrations.RemoveField(
            model_name='bidrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='browserecord',
            name='item',
        ),
        migrations.RemoveField(
            model_name='browserecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='depositdeduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='depositrecord',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='depositrecord',
            name='item',
        ),
        migrations.RemoveField(
            model_name='depositrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='depositrefundrecord',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='order',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='balance',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (2, '不正常')], default=1, verbose_name='用户状态'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='AuctionItem',
        ),
        migrations.DeleteModel(
            name='AuctionItemDetail',
        ),
        migrations.DeleteModel(
            name='AuctionItemImage',
        ),
        migrations.DeleteModel(
            name='AuctionTask',
        ),
        migrations.DeleteModel(
            name='BidRecord',
        ),
        migrations.DeleteModel(
            name='BrowseRecord',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='DepositDeduct',
        ),
        migrations.DeleteModel(
            name='DepositRecord',
        ),
        migrations.DeleteModel(
            name='DepositRefundRecord',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
