# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-10-01 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211001_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (2, '失效')], default=1, verbose_name='话题状态'),
        ),
    ]
