# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-10-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_topic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (9, '删除')], default=1, verbose_name='状态'),
        ),
    ]
