# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-10-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_department_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('cover', models.CharField(max_length=128, verbose_name='封面')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('author', models.CharField(max_length=32, verbose_name='作者名')),
                ('url', models.CharField(max_length=128, verbose_name='下载链接')),
            ],
        ),
    ]
