# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-10-01 17:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agreebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreemessage',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=512, verbose_name='吐槽内容'),
        ),
    ]
