# Generated by Django 2.1.8 on 2021-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211002_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (2, '不正常')], default=1, verbose_name='用户状态')),
            ],
        ),
        migrations.AlterField(
            model_name='agreemessage',
            name='content',
            field=models.CharField(max_length=1024, verbose_name='内容'),
        ),
    ]
