# Generated by Django 2.1.8 on 2021-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211004_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreebook',
            name='content',
            field=models.CharField(default=1, max_length=1024, verbose_name='详细内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreebook',
            name='desc',
            field=models.CharField(default=1, max_length=256, verbose_name='概要'),
            preserve_default=False,
        ),
    ]
