# Generated by Django 2.1.8 on 2021-10-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211004_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreebook',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (9, '删除')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (9, '删除')], default=1, verbose_name='用户状态'),
        ),
    ]
