# Generated by Django 2.1.8 on 2021-10-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211005_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='depart_status',
            field=models.PositiveIntegerField(choices=[(1, '已认证'), (2, '认证中'), (3, '驳回')], default=1, verbose_name='部门认证状态'),
        ),
    ]
