# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-09-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20200217_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=128, verbose_name='封面')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='位置')),
                ('favor_count', models.PositiveIntegerField(default=0, verbose_name='赞数')),
                ('viewer_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreePoint', to='api.UserInfo', verbose_name='发布者')),
            ],
        ),
        migrations.CreateModel(
            name='AgreePointDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='用于以后在腾讯对象存储中删除', max_length=128, verbose_name='腾讯对象存储中的文件名')),
                ('cos_path', models.CharField(max_length=128, verbose_name='腾讯对象存储中图片路径')),
                ('agreePoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AgreePoint', verbose_name='赞点')),
            ],
        ),
        migrations.CreateModel(
            name='AgreePointFavorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreePoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AgreePoint', verbose_name='赞点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='点赞用户')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newsdetail',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsfavorrecord',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsfavorrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentrecord',
            name='news',
        ),
        migrations.RemoveField(
            model_name='viewerrecord',
            name='news',
        ),
        migrations.AlterField(
            model_name='commentfavorrecord',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CommentRecord', verbose_name='赞点'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '待收货'), (3, '已完成'), (4, '逾期未支付'), (5, '支付中')], verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsDetail',
        ),
        migrations.DeleteModel(
            name='NewsFavorRecord',
        ),
        migrations.AddField(
            model_name='commentrecord',
            name='agreePoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.AgreePoint', verbose_name='赞点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewerrecord',
            name='agreePoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.AgreePoint', verbose_name='赞点'),
            preserve_default=False,
        ),
    ]
